# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
